version: '2'

services:
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  service:
    image: flask
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "8080:5000"
    depends_on:
      - mongo
