version: '2'

services:
  db:
    container_name: postgresql
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  service:
    image: flask
    environment:
      - DB_HOST=postgresql
    ports:
      - "8080:5000"
    depends_on:
      - db
