apiVersion: v1
kind: Pod
metadata:
  name: app-db
  labels:
    app: app-db
spec:
  restartPolicy: Never

  volumes:
  - name: mongo-volume
    emptyDir: {}

  containers:
  - name: mongo
    image: mongo
    ports:
      - containerPort: 27017
    volumeMounts:
    - name: mongo-volume
      mountPath: /data/mongo

  - name: flask
    image: flask:2
    ports:
    - containerPort: 5000
    env:
    - name: MONGO_HOST
      value: "localhost" # containers in same pod run on localhost
    - name: MONGO_PORT
      value: "27017"


# kubectl create -f pod-app-db.yaml
# kubectl expose pod app-db
# minikube service app-db --url
