apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    volumeMounts:
    - name: mongo-volume
      mountPath: /data/mongo
  volumes:
  - name: mongo-volume
    emptyDir: {}

# kubectl create -f pod-mongo.yaml
