apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stage-ns
  name: view-stage-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services", "deployments", "pods", "pods/log", "nodes", "secrets", "configMaps"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-stage-rb
#  namespace: stage-ns DO we need to mention ns here? since role is already binded to ns
roleRef:
  kind: Role
  name: view-stage-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: frodo
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: bilbo
  apiGroup: rbac.authorization.k8s.io
