apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
#  namespace: stage  // cluster role not restricted to namespace
  name: reader-cluster-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources:
    - services
    - deployments
    - pods
    - pods/log
    - ingresses
    - serviceaccounts
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - pods/portforward
  verbs:
    - create
