apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
#  namespace: stage  // cluster role not restricted to namespace
  name: reader-cluster-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources:
    - services
    - deployments
    - statefulsets
    - replicasets
    - pods
    - pods/log
    - ingresses
    - configmaps
    - serviceaccounts
    - persistentvolumes
    - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
