name: Flask build image

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up python
      uses: actions/setup-python@v1.0.0
      with:
        python-version: '3.7'
        architecture: 'x64'
    
    - name: Prepare venv
      run: |
        python3 -m venv ./venv
        source venv/bin/activate
        pip install -r requirements.txt 
      
    - name: Test
      # `run` launches another shell so need to activate venv one more time
      run: |
        source venv/bin/activate
        pytest backend/tests
        
    - name: Build image
      # TODO try using $GITHUB_REPOSITORY instead of hardcoded owner/repo
      # https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#github_token-secret
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE_ORIGIN: "docker.pkg.github.com/avbelyaev/k8s-rbac-experiments/flask-sample"
      run: |
        # build image
        docker build -t ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA} .
        docker tag ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA} ${DOCKER_IMAGE_ORIGIN}:latest

        # log in
        docker login docker.pkg.github.com --username avbelyaev --password ${TOKEN}

        # rewriting image evrytime since its just a test
        docker push ${DOCKER_IMAGE_ORIGIN}:latest

#    - name: Deploy new version
      # TODO: create separate job for this
      # version: sha
      # try ssh ubuntu@35.180.103.209 "cd /home/flask; sudo docker-compose up -d --force-rebuild"
